name: Ansible Bird Configuration Example on a Mac Self Hosted Runner 

on: workflow_dispatch

jobs:
  automated-api-tests:
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v3
      - name: Run Ansible
        run: |
          cd demos/demo7/bird && /usr/local/bin/ansible-playbook ./playbook.yml 
