name: Postman HTTPBin Example on a K8s Self Hosted Runner with Super-Linter

on: workflow_dispatch

jobs:
  automated-api-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh 
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "26663889-d4fb9c01-344b-4961-a11c-b8f158219e0f" -e "26663889-234dee14-7ed6-475c-b292-449a861cc8e8"
